/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2017-03-20 19:01:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class test2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <!-- Theme Made By www.w3schools.com - No Copyright -->\r\n");
      out.write("  <title>Bootstrap Theme Simply Me</title>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Montserrat\" rel=\"stylesheet\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <script type=\"text/javascript\" src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"../js/jquery.maphilight.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <script>$(function() {\r\n");
      out.write("        $('.map').maphilight({\r\n");
      out.write("            fillColor: 'ffb31a'\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        });\r\n");
      out.write("     \r\n");
      out.write("    });</script> \r\n");
      out.write("  <style>\r\n");
      out.write("  body {\r\n");
      out.write("      font: 20px Montserrat, sans-serif;\r\n");
      out.write("      line-height: 1.8;\r\n");
      out.write("      color: #f5f6f7;\r\n");
      out.write("      margin: 0;\r\n");
      out.write("  }\r\n");
      out.write("  p {font-size: 16px;}\r\n");
      out.write("  .margin {margin-bottom: 45px;}\r\n");
      out.write("  .bg-0{\r\n");
      out.write("    background-color: #F8F8F8;\r\n");
      out.write("    color: #555555;\r\n");
      out.write("    font-size: 50;\r\n");
      out.write("  }\r\n");
      out.write("  .bg-1 { \r\n");
      out.write("      background-color: #ffffff; /* Green */\r\n");
      out.write("      color: #555555;\r\n");
      out.write("  }\r\n");
      out.write("  .bg-2 { \r\n");
      out.write("      background-color: #474e5d; /* Dark Blue */\r\n");
      out.write("      color: #ffffff;\r\n");
      out.write("  }\r\n");
      out.write("  .bg-3 { \r\n");
      out.write("      background-color: #ffffff; /* White */\r\n");
      out.write("      color: #555555;\r\n");
      out.write("  }\r\n");
      out.write("  .bg-4 { \r\n");
      out.write("      background-color: #2f2f2f; /* Black Gray */\r\n");
      out.write("      color: #fff;\r\n");
      out.write("  }\r\n");
      out.write("  .container-menu {\r\n");
      out.write("      padding-top: 10px;\r\n");
      out.write("      padding-bottom: 10px;\r\n");
      out.write("  }\r\n");
      out.write("  .container-fluid {\r\n");
      out.write("      padding-top: 70px;\r\n");
      out.write("      padding-bottom: 70px;\r\n");
      out.write("  }\r\n");
      out.write("  .navbar {\r\n");
      out.write("      padding-top: 15px;\r\n");
      out.write("      padding-bottom: 15px;\r\n");
      out.write("      border: 0;\r\n");
      out.write("      border-radius: 0;\r\n");
      out.write("      margin-bottom: 0;\r\n");
      out.write("      font-size: 12px;\r\n");
      out.write("      letter-spacing: 5px;\r\n");
      out.write("  }\r\n");
      out.write("  .navbar-nav  li a:hover {\r\n");
      out.write("      color: #1abc9c !important;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- Navbar -->\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<!-- First Container -->\r\n");
      out.write("\r\n");
      out.write("<!-- <div class=\"container-fluid bg-0 text-center\">\r\n");
      out.write("   \r\n");
      out.write("          <h1 >Smart House</h1>\r\n");
      out.write("  <h3>One click to control your house</h3>\r\n");
      out.write("        \r\n");
      out.write("</div> -->\r\n");
      out.write("<div class=\"container-fluid bg-1 \">\r\n");
      out.write("   \r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("    <div class=\"col-sm-6\">\r\n");
      out.write("        \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<img  src=\"FloorPlan_2BRFLAT_Tgivingl1_900.jpg\" class=\"map\" usemap=\"#features\">\r\n");
      out.write("\r\n");
      out.write("<map name=\"features\">\r\n");
      out.write("\t\t\r\n");
      out.write("  \t\t\t \r\n");
      out.write("     <area  href=\"smartHouse?searchAction=searchByCity&room=Patio\" coords=\"120,488,387,678\" shape=\"rect\">\r\n");
      out.write("    <area  href=\"smartHouse?searchAction=searchByCity&room=SmallCloset\" coords=\"388,487,458,602\" shape=\"rect\">\r\n");
      out.write("    <area  href=\"smartHouse?searchAction=searchByCity&room=BedRoom\" coords=\"390,273,643,483\" shape=\"rect\">\r\n");
      out.write("    <area   href=\"smartHouse?searchAction=searchByCity&room=BathRoom\" coords=\"428,21,593,127\" shape=\"rect\">\r\n");
      out.write("    <area   href=\"smartHouse?searchAction=searchByCity&room=BathRoom1\" coords=\"598,21,759,126\" shape=\"rect\">\r\n");
      out.write("    <area href=\"smartHouse?searchAction=searchByCity&room=BigCloset\" coords=\"762,20,875,124\" shape=\"rect\">\r\n");
      out.write("    <area  href=\"smartHouse?searchAction=searchByCity&room=Kitchen\" coords=\"22,243,119,250,165,152,218,154,219,19,22,18\" shape=\"poly\">\r\n");
      out.write("    <area  href=\"smartHouse?searchAction=searchByCity&room=LivingRoom\" coords=\"427,129,388,127,387,480,118,484,121,249,167,153,219,150,218,22,420,27\" shape=\"poly\">\r\n");
      out.write("    <area  href=\"smartHouse?searchAction=searchByCity&room=Hall\" coords=\"388,132,597,269\" shape=\"rect\">\r\n");
      out.write("    <area  href=\"smartHouse?searchAction=searchByCity&room=BedRoom1\" coords=\"603,132,597,264,641,271,643,403,874,401,877,131\" shape=\"poly\">\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("</map>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-sm-6\"></div>\r\n");
      //  c:choose
      org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("  ");
          //  c:when
          org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
          _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
          _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
          // /jsp/test2.jsp(124,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${room.name != 'Null'}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
          int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
          if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\r\n");
              out.write("    ");

    response.setIntHeader("Refresh", 60); //in your case 60*5=300 (for 5 min)
    
              out.write("\r\n");
              out.write("    <h3><b>Information</b></h3>\r\n");
              out.write("    <p>Room Name: ");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${room.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write("  </p>\r\n");
              out.write("\r\n");
              out.write("    <p>Temp: ");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${room.temp}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write("</p>\r\n");
              out.write("    <p>Window Open: ");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${room.windowOpen}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write("</p>\r\n");
              out.write("    <p>Lights On: ");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${room.lightsOn}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write("</p>\r\n");
              out.write("    \r\n");
              out.write("    \r\n");
              out.write("   \r\n");
              out.write("    \r\n");
              out.write("    <br>\r\n");
              out.write("    <br>\r\n");
              out.write("    <form action=\"/smartHouse\" method=\"post\">\r\n");
              out.write("    <b><h3>Controls</h3></b>\r\n");
              out.write("\r\n");
              out.write("    <p>Temp: <input type=\"number\" name=\"temp\" min=\"5\" max=\"40\" value=\"");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${room.temp}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write("\"/></p>\r\n");
              out.write("    <p>Window Open:\r\n");
              out.write("    <input type=\"radio\" ");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['room'].windowOpen == true? 'checked':''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write(" name=\"windows\" value=\"True\" /> Open\r\n");
              out.write("    <input type=\"radio\" ");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['room'].windowOpen == false? 'checked':''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write(" name=\"windows\" value=\"False\" /> Closed\r\n");
              out.write("    </p>\r\n");
              out.write("    <p>Lights On: \r\n");
              out.write("    <input type=\"radio\" ");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['room'].lightsOn == true? 'checked':''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write(" name=\"light\" value=\"True\" /> On\r\n");
              out.write("    <input type=\"radio\" ");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['room'].lightsOn == false? 'checked':''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write(" name=\"light\" value=\"False\" /> Off\r\n");
              out.write("    </p>\r\n");
              out.write("    \r\n");
              out.write("    \r\n");
              out.write("   \r\n");
              out.write("    <p>Submit button.\r\n");
              out.write("    <input type=\"submit\" name=\"submit\" value=\"submit\" /></p>\r\n");
              out.write("</form>\r\n");
              out.write("\r\n");
              out.write("    ");
              int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
            return;
          }
          _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
          out.write("\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("<footer class=\"container-fluid bg-4 text-center\">\r\n");
      out.write("  <p>Smart House by <a href=\"https://github.com/Przecich\">Przemyslaw Cich</a></p> \r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
